### ISSUE TITLE
AIM; SmartIndirect fire

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/CustomBundle#13]
This feature is not working properly. If I have a shot that has an obstructed weapon (any DF weapon) and decide only to fire an indirect fire LRM. The Penalties are not switching as they should.  see the screenshots as they are worth 1000 words.  The first screenshot shows the improper penalties applied. I took the meck and moved it to show the second and it should be these penalties. CAC is a mess and some serious time needs to be spent verifying AIM is working correctly, I know AIM is highly advanced piece of code but as you chose to incorporate it exclusively then it needs to be maintained properly otherwise it should be removed and let the author fix the issues, even though he hasn't been around in a long time he might fix it one last time! Just a thought.
![20200801144948_1](https://user-images.githubusercontent.com/45599120/89110454-006a1300-d408-11ea-9711-d4af90ca6740.jpg)
![20200801145018_1](https://user-images.githubusercontent.com/45599120/89110457-03fd9a00-d408-11ea-8898-1cd77b466708.jpg)

**Comment by xeryx01** [comment]
Also see how the Icons on the left panel are not loading. Maybe there this info is not getting properly loaded during missions. it is sporadic to figure out with only the console.

**Comment by CMiSSioN** [comment]
smart indirect switched off until fixed
icons loading fixed
