### ISSUE TITLE
AMS Graphical effects not working correctly

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/CustomBundle#14]
I have tried a tone of different configs, even the ams version in the custom ammo. The lasers are not displaying like they used to. The machine gun version seems to work fine.  It is only the lasers being displayed firing. the item is working. Can you please try on your end. This occurs in both skirmis and campaign.

**Comment by xeryx01** [comment]
After EXTENSIVE testing of the AMS systems and using the provided AMS systems by CUSTOM BUNDLE.  I was able to narrow down the issues. The missiles and MG's AMS's work properly in showing the graphic.  The ones that DO NOT work are Guass, Balistic, and Laser.  Again it is only the graphics that are not showing, the AMS works fine. Please look into this issue and correct it.

**Comment by CMiSSioN** [comment]
fixed
