### ISSUE TITLE
CAC and Heavy metal are not compatible

### ISSUE THREAD

**Issue by shaygover** [BattletechModders/CustomBundle#7]
Hi CMiSSioN,

I bought heavy metal yesterday. After some debug, I noticed that CAC and LB #-X ammo don't play well together. Can you help?

Debug done: Adding mods one by one and checking. Also tried to set locked to false in mod.json.

I used both release 0.2.27 and 0.2.19. Logs are from 0.2.27.

Game and CAC logs (Other CAC logs are empty)
[CAC_main_log.txt](https://github.com/BattletechModders/CustomBundle/files/4546203/CAC_main_log.txt)
[ModTek.log](https://github.com/BattletechModders/CustomBundle/files/4546215/ModTek.log)
[Player.log](https://github.com/BattletechModders/CustomBundle/files/4546217/Player.log)

FLYS clean log:
[cleaned_output_log.txt](https://github.com/BattletechModders/CustomBundle/files/4546208/cleaned_output_log.txt)

And a pic showing the problem:
![2020-04-28_16-01](https://user-images.githubusercontent.com/10381553/80497195-ca357700-8972-11ea-86b0-4464e41a4c57.png)

**Comment by LadyAlekto** [comment]
cac is a framework, not a mod, you have to adjust your mods to use cac

**Comment by shaygover** [comment]
I see. But it's not a mod. It's heavy metal DLC.

There is also a mod I would like to use (https://github.com/mad2342/StreakMissileLaunchers) that'll require some adjusting. Is there a guide somewhere?

**Comment by Radromity** [comment]
cac is not a dlc. thank you, come again.

**Comment by shaygover** [comment]
@Radromity I don't understand. CAC is a mod. Heavy Metal is a DLC.
What am I missing?

**Comment by LadyAlekto** [comment]
CAC is a framework
Its to MAKE MODS with it
Its not meant to be used as a mod

This like with the jump jets has very little to do with cac and very much to do with you not understanding it

**Comment by shaygover** [comment]
I don't understand. Can you clarify?

**Comment by wmtorode** [comment]
what is meant is that CAC itself is not a mod, it is a framework that you use to build a mod on top of it.

you cant just add it in like a mod or change a few settings and expect it to work. you need to very carefully read its documentation. then adjust the settings to your needs. then create or adjust the rest of your mod accordingly.

CAC works just fine with heavy metal if you use it correctly as it is part of RT and BTA both of which work with Heavy Metal.

**Comment by CMiSSioN** [comment]
wmtorode, thanks for protection :) but unfortunately problem is not described in documentation.
shaygover, problem is for unknown reason HM's ammo definitions LBX, Narc, Inferno contains both ammo type fields (new style "ammunitionTypeID" and old "Category") and this values conflicting each other. 
CAC it is framework and some mods relay on it, so have to provide backward compatibility for modders do not want to change all their hundreds of ammo and weapon definitions. That is why CAC pays attention both fields new and old. If both set you get unpredictable behavior like this. 
RT and BTA have no this problem cause this mods implemented own LBX, Narc and Inferno long time ago. 
To workaround this, i suggest to mod HM's ammo definitions removing one of conflicting fields
JSONs can be get there https://github.com/caardappel-hbs/bt-dlc-designdata

**Comment by shaygover** [comment]
Thank you both.
I use CAC as a mod because it includes AIM and WR. Maybe it's better if
I'll looks for forks of this mods.
Originally I used it because it's a dependency of Royal SLDF mod but that
mod hasn't been updated in the last year and it caused game crashes in the
mid stage if the campaign (After Welderly). So I stopped using it. Now I
use CAC only for it's non ammo categories changes.
