### ISSUE TITLE
Unexplainable heat issue with CB2.48 (CAC)

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/CustomBundle#8]
An unexplainable issue with heat. Things were going fine then when I unselected some LRM weapons because I did not need to fire them then heat overflowed, and it would have been shutdown situation???

Here is my main logs
[CAC_main_log.txt](https://github.com/BattletechModders/CustomBundle/files/4708027/CAC_main_log.txt)

**Comment by CMiSSioN** [comment]
fixed
